version: '3.8'

services:
  frontend:
    build:
      context: ./cml-test-client
      dockerfile: Dockerfile
    ports:
      - "5173:80"  # Map port 5173 on the host to port 80 in the container
    depends_on:
      - backend
    command: ["npm", "run", "dev"]  # Override the default command to run the development server

  backend:
    build:
      context: ./cml-test-server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://db:5432/postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: